### PR TITLE
Subset tidal reaches

### LINKED ISSUE #241: How are we accounting for tidal sites?
We currently use a few different approaches to try to restrict our analysis to inland (freshwater) streams in the DRB, including excluding sites along the mainstem Delaware River below the head-of-tide in ~Trenton and only requesting certain NWIS site types. Based on initial analysis of the model residuals it seems like some tidal sites remain in the dataset and are potentially skewing model error. 

I want to revisit, how are we accounting for tidal sites in the discrete WQP data? Is there another filtering step we should use when creating the input data?

### PR DESCRIPTION
**Pull request by lekoenig**
This PR adds a new target `p2_tidal_reaches_sf` that represents the subset of PRMS segments that may be tidally-influenced. We assume these reaches are tidal based solely on the `tidal` attribute from NHDPlus. 

To work with the NHDPlus data I've also added a new helper target, `p2_drb_comids_seg`, that contains the NHDPlusV2 COMID's that intersect/overlap the PRMS network. This code subsets these "mainstem" COMIDs to retain those with `tidal == 1` in the NHDPlus attribute table. Using the crosswalk table, I assumed all PRMS segments with at least one "tidal" COMID are also tidal. As we've discussed, this assumption is probably conservative and so I'm happy to continue that discussion and iterate our methods here. 

I have a couple small questions: 

- I haven't run the pipeline or committed the meta file because it's been awhile since I've interacted with the repo. Let me know if you have a preference for what I should do.
- Right now the tidal reaches subset is formatted as an `sf` data frame. Do you have a preference between that output versus a character string with the tidal `subsegid`?

image

Relates to #241

### CODE REVIEW

**Comment by jds485** [comment]
> I haven't run the pipeline or committed the meta file because it's been awhile since I've interacted with the repo. Let me know if you have a preference for what I should do.

It will take a while to build local file targets, so I can run this when it's ready. 

> Do you have a preference between that output versus a character string with the tidal subsegid?
I'd prefer a vector of strings with the subsegid

**Review by jds485 — APPROVED** [review]
This looks good to me. See my comment about running the code. Let me know if I should run it in the container if you don't have that set up

**Comment by lekoenig** [comment]
> I'd prefer a vector of strings with the subsegid

Sounds good, I just pushed a commit to return the `subsegid` as a character vector instead of an sf object. In the meantime, here's what that looks like:

```r
subset_tidal_reaches(p1_reaches_sf, p2_drb_comids_seg)
Spherical geometry (s2) switched off
Spherical geometry (s2) switched on
  [1] "59_1"   "64_1"   "65_1"   "330_1"  "332_1"  "333_1"  "341_1"  "342_1"  "343_1"  "344_1"  "345_1"  "346_1"  "347_1"  "351_1"  "352_1"  "353_1"  "356_1"  "361_1" 
 [19] "362_1"  "363_1"  "366_1"  "370_1"  "374_1"  "376_1"  "377_1"  "378_1"  "379_1"  "380_1"  "381_1"  "382_1"  "383_1"  "384_1"  "385_1"  "386_1"  "387_1"  "388_1" 
 [37] "389_1"  "390_1"  "391_1"  "393_1"  "394_1"  "395_1"  "396_1"  "590_1"  "591_1"  "593_1"  "599_1"  "601_1"  "606_1"  "607_1"  "613_1"  "614_1"  "893_1"  "895_1" 
 [55] "904_1"  "905_1"  "1252_1" "1253_1" "1254_1" "1255_1" "1256_1" "1257_1" "1259_1" "1261_1" "1262_1" "1263_1" "1264_1" "1265_1" "1266_1" "2124_1" "2125_1" "2129_1"
 [73] "2130_1" "2131_1" "2132_1" "2137_1" "2138_1" "2139_1" "2140_1" "2748_1" "2749_1" "2750_1" "2751_1" "2752_1" "2753_1" "2754_1" "2755_1" "2756_1" "2757_1" "2758_1"
 [91] "2759_1" "2760_1" "2761_1" "2762_1" "2763_1" "2764_1" "2765_1" "2766_1" "2767_1" "2768_1" "2769_1" "2770_1" "2771_1" "2772_1" "2796_1" "2797_1"
```

> Let me know if I should run it in the container if you don't have that set up

There's no spatial processing in this function. I didn't see a target where we had already saved NHDv2 flowlines, so we download those using nhdplusTools, but otherwise, everything is tabular using the crosswalk. I can run containers on my local machine but I don't believe I've ever run _this_ pipeline from within the container. I could do that, but if it'd take less than ~1 hr for you to run it I might prefer that (or I could try `tar_make()`'ing just these two targets.

**Comment by jds485** [comment]
Okay, I can run this. It will take a few minutes and I'll push the meta file

**Comment by jds485** [comment]
> Also, should I hold off until I've had a chance to take a look at the refined-elevation approach from https://github.com/USGS-R/drb-inland-salinity-ml/issues/241?

yes

**Comment by lekoenig** [comment]
I just pushed a new commit d28c1a52578202e3e4aa344da4b319b73299e96a to refine the elevation used to define tidal segments in the DRB. See [this](https://github.com/USGS-R/drb-inland-salinity-ml/issues/241#issuecomment-1557484335) comment in #241 for more details.

**Review by jds485 — APPROVED** [review]
This looks good to me. I am going to rebuild the pipeline and I'll also add a (possibly temporary) txt file target with these segments that I'll use to filter the datasets in a Python function

**Comment by jds485** [comment]
Closes #241

**Pull request merged**
